# Generated by Django 3.1.7 on 2021-03-05 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
